FROM python:3.6

RUN apt-get update && apt-get install -y libmemcached-dev

RUN pip install -U pipenv==8.3.2

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

RUN pipenv install --deploy --system

COPY . /usr/src/app
