FROM python:3.6

RUN apt-get update && apt-get install -y libmemcached-dev

RUN pip install -U pipenv==8.3.2

ADD . /code
WORKDIR /code

COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

RUN pipenv install --deploy --system

EXPOSE 5000

CMD ["sh", "docker-entrypoint.sh"]
