FROM python:3.6

RUN apt-get update && apt-get install -y libmemcached-dev && pip install pipenv

ADD . /code
WORKDIR /code

RUN pipenv install --deploy --system

EXPOSE 5000

CMD ["sh", "docker-entrypoint.sh"]
